# Generated by Django 5.2.3 on 2025-06-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
