# Generated by Django 5.2.3 on 2025-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriberprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
