# Generated by Django 5.2.3 on 2025-06-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriberprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
